// <auto-generated />
using System;
using Erp.DataAccessLayer.Concrete.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Erp.DataAccessLayer.Migrations
{
    [DbContext(typeof(ErpContext))]
    [Migration("20260507205447_InitialBaseline")]
    partial class InitialBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Erp.EntityLayer.Entities.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ISIM");

                    b.HasKey("CityId");

                    b.ToTable("TBL_IL");
                });

            modelBuilder.Entity("Erp.EntityLayer.Entities.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Erp.EntityLayer.Entities.Customer", b =>
                {
                    b.Property<string>("CustomerCode")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("MUSTERI_KODU");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ADRES");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IL");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MUSTERI_ADI");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ILCE");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("E_POSTA");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TELEFON");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TIP");

                    b.HasKey("CustomerCode");

                    b.ToTable("TBL_MUSTERIKAYITLARI");
                });

            modelBuilder.Entity("Erp.EntityLayer.Entities.District", b =>
                {
                    b.Property<int>("DistrictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistrictId"));

                    b.Property<int?>("DistrictCity")
                        .HasColumnType("int")
                        .HasColumnName("IL_ID");

                    b.Property<string>("DistrictName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ISIM");

                    b.HasKey("DistrictId");

                    b.ToTable("TBL_ILCE");
                });

            modelBuilder.Entity("Erp.EntityLayer.Entities.GroupCode", b =>
                {
                    b.Property<string>("GroupCodeValue")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("GRUP_KODU");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GRUP_ADI");

                    b.HasKey("GroupCodeValue");

                    b.ToTable("TBL_GRUPKOD");
                });

            modelBuilder.Entity("Erp.EntityLayer.Entities.Order", b =>
                {
                    b.Property<string>("OrderCode")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("SIPARIS_NO");

                    b.Property<string>("CustomerCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MUSTERI_KODU");

                    b.Property<string>("OrderDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SIPARIS_TARIHI");

                    b.Property<string>("OrderDeliveryDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TESLIM_TARIHI");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(18, 3)")
                        .HasColumnName("TOPLAM_TUTAR");

                    b.HasKey("OrderCode");

                    b.ToTable("TBL_SIPARISLER");
                });

            modelBuilder.Entity("Erp.EntityLayer.Entities.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SIPKALEM_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("URUN_ACIKLAMASI");

                    b.Property<string>("OrderCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SIPARIS_NO");

                    b.Property<decimal?>("OrderItemAmount")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("MIKTAR");

                    b.Property<string>("OrderItemStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("URETIMDURUMU");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("FIYAT");

                    b.Property<string>("StockCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("STOK_KODU");

                    b.Property<string>("StockName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("STOK_ADI");

                    b.Property<decimal?>("Vat")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("KDV");

                    b.HasKey("OrderItemId");

                    b.ToTable("TBL_SIPARISKALEMLERI");
                });

            modelBuilder.Entity("Erp.EntityLayer.Entities.ProductionResult", b =>
                {
                    b.Property<string>("ProductionResultCode")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("URETIMSONUKAYDI_NUMARASI");

                    b.Property<string>("CustomerCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MUSTERI_KODU");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MUSTERI_ADI");

                    b.Property<string>("OrderCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SIPARIS_NUMARASI");

                    b.Property<int?>("OrderItemId")
                        .HasColumnType("int")
                        .HasColumnName("SIPKALEM_ID");

                    b.Property<decimal?>("ProductionResultAmount")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("MIKTAR");

                    b.Property<string>("StockCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("STOK_KODU");

                    b.Property<string>("StockName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("STOK_ADI");

                    b.Property<string>("WorkOrderCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ISEMRI_NUMARASI");

                    b.HasKey("ProductionResultCode");

                    b.ToTable("TBL_URETIMSONUKAYITLARI");
                });

            modelBuilder.Entity("Erp.EntityLayer.Entities.Stock", b =>
                {
                    b.Property<string>("StockCode")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("STOK_KODU");

                    b.Property<string>("GroupCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GRUP_KODU");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 3)")
                        .HasColumnName("FIYAT");

                    b.Property<string>("StockName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("STOK_ADI");

                    b.Property<decimal?>("Vat")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("KDV_ORANI");

                    b.HasKey("StockCode");

                    b.ToTable("TBL_STOKKAYITLARI");
                });

            modelBuilder.Entity("Erp.EntityLayer.Entities.StockMovement", b =>
                {
                    b.Property<int>("StockMovementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("STOKHAREKET_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockMovementId"));

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MUSTERI_ADI");

                    b.Property<decimal?>("IncomingAmount")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("G_MIKTAR");

                    b.Property<decimal?>("OutgoingAmount")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("C_MIKTAR");

                    b.Property<string>("ProductionResultCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("URETIMSONUKAYDI_NUMARASI");

                    b.Property<string>("ProductionResultDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ACIKLAMA");

                    b.Property<string>("StockCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("STOK_KODU");

                    b.Property<string>("StockName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("STOK_ADI");

                    b.Property<string>("WorkOrderCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ISEMRI_NUMARASI");

                    b.HasKey("StockMovementId");

                    b.ToTable("TBL_STOKHAREKETLERI");
                });

            modelBuilder.Entity("Erp.EntityLayer.Entities.WorkOrder", b =>
                {
                    b.Property<string>("WorkOrderCode")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ISEMRI_NUMARASI");

                    b.Property<string>("DeliveryDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TESLIM_TARIHI");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ISEMRI_ACIKLAMASI");

                    b.Property<string>("OrderCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SIPARIS_NO");

                    b.Property<int?>("OrderItemId")
                        .HasColumnType("int")
                        .HasColumnName("SIPKALEM_ID");

                    b.Property<string>("StockCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("STOK_KODU");

                    b.Property<string>("StockName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("STOK_ADI");

                    b.Property<decimal?>("WorkOrderAmount")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("MIKTAR");

                    b.Property<string>("WorkOrderDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ISEMRI_TARIHI");

                    b.Property<string>("WorkOrderStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DURUM");

                    b.HasKey("WorkOrderCode");

                    b.ToTable("TBL_ISEMRI");
                });
#pragma warning restore 612, 618
        }
    }
}
